# Generated by Django 3.2.9 on 2021-12-03 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.users'),
        ),
    ]
