# Generated by Django 3.2.9 on 2021-12-03 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_posts_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user_id',
            new_name='user',
        ),
    ]
