# Generated by Django 3.2.9 on 2021-12-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_users_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='user',
        ),
        migrations.AddField(
            model_name='posts',
            name='user',
            field=models.ManyToManyField(to='blog.Users'),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
